### ISSUE TITLE
Record failed missions

### ISSUE THREAD

**Issue by Nillx** [teelolws/TLDRMissions#15]
Hello and thanks  for making this addon, its been awhile since we had a proper mission addon! 

Back when Venture Plan was in development they had an option to record failed missions and then we were able to send the report to the author.  Do you think something like this could be helpful here too?

**Comment by teelolws** [comment]
Yes. That was already implemented recently. If a mission that was started by this addon fails, it will save a log and prompt you to upload it here. _The addon version when the mission was started and when the mission was completed have to be the same._ So if you've updated the addon since you started the mission, it won't prompt you, because I may have fixed the problem since you started it.

**Comment by Nillx** [comment]
Great thanks, im currently simming missions with your addon and then checking what does VP shows to see if its showing a different outcome. This is for Necrolord.
