### ISSUE TITLE
[BUG] A mission failed! (night fae)

### ISSUE THREAD

**Issue by Nillx** [teelolws/TLDRMissions#26]
Had to convert it to txt
[TLDRMissions.txt](https://github.com/teelolws/TLDRMissions/files/8498221/TLDRMissions.txt)

**Comment by teelolws** [comment]
Thanks. Heres the first discrepancy I've spotted:

Blizzard came up with

    Confused Automa cast   Attack Wave at Ardenweald Grovetender[1340HP] for 40  damage.

But TLDR was expecting

    Confused Automa[6][5065HP] attacks Ardenweald Grovetender[3][1339HP] for 41

Doesn't seem like much, but over 20 turns it can make the difference between a troop living and dying, and being alive long enough to get a finishing blow to win.

The base attack of Confused Automa is 207, Attack Wave does 25% of 207, and it also had the debuff "Bramble Trap", which reduces its damage by another 20%. The problem there is rounding: .25*207 = 51.75, .8*51.75 = 41.4 which TLDR then rounded to 41. But Blizzard seems to be rounding down at each step. .25*207 = 51.75 which they then round down to 51, then .8*51 = 40.8 which they round down to 40.

Second discrepancy:

Blizzard came up with:

    Confused Automa   meleed Meatball[1995HP] for 227 damage.

But TLDR was expecting:

    Confused Automa[6][3306HP] attacks Meatball[2][2007HP] for 215

Confused Automa had Bramble Trap (-20% damage), and Meatball had MEATBALL MAD!! (+62 damage taken).

After changing the order of operations for the damage calculation, and adding more rounding, the problem is solved.

Fixes will be going up in 9.2-017 later today.

**Comment by Nillx** [comment]
Great thanks for fixing and adding stuff so quickly!
