### ISSUE TITLE
[BUG] Other verry long calculations since 027 verssion.

### ISSUE THREAD

**Issue by czullo** [teelolws/TLDRMissions#80]
Hi, since 027 ver. calculations on some missions are extremly long. On character that allmost all misions was like instant calculated now even missions below my companions lvl are calculated like over 100k calculations and no succes. Like on screen below. Mission was non-rare lvl 49
![WoWScrnShot_042422_181027](https://user-images.githubusercontent.com/13511496/164985615-faca8245-fe92-4e79-af88-7a8517ac7f1c.jpg)

**Comment by teelolws** [comment]
Break the Briarbane is a level 60 Elite mission: https://www.wowhead.com/mission=2266/break-the-briarbane

And you have the slider set to 10, so its trying every follower from level 50 upwards to try and beat it. I suggest you lower that slider. Since about 5 patches ago I lowered the default for that slider to 3.

Its just a very difficult mission, and it can't find a solution for it. And you have a lot of available followers. Thats a lot of permutations to try before it concludes it can't win!
