### ISSUE TITLE
Feature request: Accountwide advanced settings

### ISSUE THREAD

**Issue by zeenk** [teelolws/TLDRMissions#81]
Could we possibly get something like a check mark button that enables account wide saved settings so we don't have to change the settings on every single alt if we decide to do some tweaks in the settings? :)

**Comment by teelolws** [comment]
I have them character specific because players might want different settings on different characters. I prefer them character-specific, and if I change them to be account-wide, you might like it, but other players will complain to make them character-specific again.

As for a checkbox, how would it know whether to load account-wide settings vs save the current character settings overwriting the account-wide settings? I'd have to use a profile system which is a bit out of my scope. If you can find a WoW Addon Library that handles options profiles I can look at integrating it.

In the meantime, if you really want account-wide settings and nothing else, I suggest you just open the .toc, and change:

    ## SavedVariablesPerCharacter: TLDRMissionsDB, TLDRMissionsOptions, TLDRMissionsLogging
    
to:

    ## SavedVariablesPerCharacter: TLDRMissionsDB, TLDRMissionsLogging
    ## SavedVariables: TLDRMissionsOptions
